
##Charcoal Burner Requirements
[charcoal_burner]
	#How much more fuel a Charcoal Burner consumes when empowered by a maxed encased fan.
	#Range: > 1
	fanMultiplier = 100
	#When set to True, an active Charcoal Burner produces the same heat as a Kindled Blaze Burner and an empowered Charcoal Burner produces the same heat as a Seething Blaze Burner. Inactive state is unaffected.
	hotBurners = true
	#How much more fuel a non-empowered Charcoal Burner consumes. Use fanMultiplier for fan-empowered burners. Intended for use with the hotBurners option, the default value of 1 is recommended otherwise.
	#Range: > 1
	baseMultiplier = 1

